# Generated by Django 3.2.5 on 2021-07-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpellInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('spell_class', models.CharField(choices=[('', 'All'), ('C', 'Cleric'), ('D', 'Druid'), ('M', 'Magic-User'), ('I', 'Illusionist')], max_length=1)),
                ('level', models.SmallIntegerField()),
                ('cast_time', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('duration_per_level', models.IntegerField(default=0)),
                ('range', models.CharField(default='', max_length=75)),
                ('aoe', models.CharField(blank=True, default='', max_length=150)),
                ('saving_throw', models.CharField(default='', max_length=75)),
                ('source', models.SmallIntegerField(default=0)),
                ('description', models.TextField(default='Missing description')),
                ('commentary', models.TextField(default='')),
            ],
            options={
                'ordering': ['spell_class', 'level', 'name'],
            },
        ),
    ]
