# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpellInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('spell_class', models.CharField(max_length=1)),
                ('level', models.SmallIntegerField()),
            ],
        ),
    ]
