"""
Detailed information on creatures.
(Currently unused in favor of BasicCreatureInfo)
"""

from dnd.roll import roll
from dnd.creature_xp import determineXP


from random import randint

import sys
def __main__():
    print (sys.getsizeof(Creature))
    print (sys.getsizeof(creature_types[0]))
    print (sys.getsizeof(Aerial))
    while True:
        name = input('Enter creature name:')
        creatures = generateCreatures(name)
        if creatures:
            for c in creatures:
                print(c)
        else:
            print('{} not found.'.format(name))

#attacks have the form [(die,num,mod),(die,num,mod),...]
#no. appearing has form (min,max)
#type HD (min,max,bonus)
#creature HD (hd,bonus)

def findCreatureType(name):
    name_tokens = name.lower().split()
    num_tokens = len(name_tokens)
    if num_tokens < 1:
        return None
    #Find initial candidates
    candidates = [c for c in creature_types
                    if name_tokens[0] in c.name.lower()] 
    
    #check if each word is within the creature's full name
    for token in name_tokens[1:]:
        candidates = [c for c in candidates
                        if token in c.name.lower()]
        
    if len(candidates) == 0:
        print('Creature type not defined.')
        return None
    elif len(candidates) > 1:
        #if there is an exact match, drop others
        if name.lower() in [c.name.lower() for c in candidates]:
            found_idx = [c.name.lower() 
                              for c in candidates].index(name.lower())
            found_creature = candidates[found_idx]
        else:
            print('Found the following monsters, be more specific:')
            for c in candidates:
                print(c.name)
            return None
    else:
        found_creature = candidates[0]

    return found_creature

def generateCreatures(name):
    type = findCreatureType(name)
    if not type:
        return None
    
    
    creature_list = []
    num = randint(type.num[0], type.num[1])
    for i in range(num):
        creature_list.append(Creature(type))
        
    return creature_list
    
class Move():
    def __init__(self,ground,air=0,water=0,burrow=0,web=0):
        self.walk_speed = ground
        self.fly_speed = air
        self.swim_speed = water
        self.burrow_speed = burrow
        self.web_speed = web

class CreatureType():
    def __init__(self,name,num,ac,move,lair,hd,attacks,m_resist,iq,
                 align,size,special=[],exceptional=[],notes=None):
        self.name = name
        self.num = num
        self.AC = ac
        self.move = move
        self.lair_chance = lair
        self.hit_die = hd
        self.attacks = attacks
        self.magic_resist = m_resist
        self.iq = iq
        self.alignment = align
        self.size_class = size
        self.special = special
        self.exceptional = exceptional
        self.notes = notes
        
    def __str__(self):
        output = self.name
        return output

class DragonType(CreatureType):
    def __init__(self,name,num,ac,move,lair,hd,attacks,m_resist,iq,
                 align,size,special=[],exceptional=[],notes=None,
                 speak=0.0,magic=0.0,sleep=0.0):
        self.speak = speak
        self.magic = magic
        self.sleep = sleep

        CreatureType.__init__(self,name,num,ac,move,lair,hd,attacks,m_resist,iq,
                            align,size,special,exceptional,notes)
 
                            
"""
DragonType('Black Dragon',
    num = (,),
    ac = ,
    move = Move(12,air=24),
    lair = 0.,
    hd = (,,),
    attacks = [(,,),(,,),(,,)],
    m_resist = 0.0,
    iq = '',
    align = '',
    size = 'L',
    special = [],
    exceptional = [],
    speak = 0.,
    magic = 0.,
    sleep = 0.
),
"""   
     
"""
CreatureType('',
    num = (,),
    ac = ,
    move = Move(12),
    lair = 0.0,
    hd = (,,),
    attacks = [(,,)],
    m_resist = 0.0,
    iq = '',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = []
),
"""

def rollHP(hit_die):
    min_hd = hit_die[0]
    max_hd = hit_die[1]
    mod = hit_die[2]
    
    hd = (randint(min_hd,max_hd), mod)
    hp = roll(8, hd[0]) + mod
    hp = max(hp,1)
    
    return [hp, hd]

#TODO Dragon spells
class Creature():
    def __init__(self, c_type):
        self.name = c_type.name
        self.hit_die = [0,0]
        self.hp = 0
        
    
        if type(c_type) == DragonType:
            r = roll(8)
            if r < 3:
                dragon_size = 'Small'
                self.hit_die = [c_type.hit_die[0],0]
            elif r < 8:
                dragon_size = 'Average'
                self.hit_die = [c_type.hit_die[0] + 1,0]
            else:
                dragon_size = 'Huge'
                self.hit_die = [c_type.hit_die[0] + 2,0]
            
            r = roll(8)
            if r == 1: age = 'Very Young'
            elif r == 2: age = 'Young'
            elif r == 3: age = 'Sub-Adult'
            elif r == 4: age = 'Young Adult'
            elif r == 5: age = 'Adult'
            elif r == 6: age = 'Old'
            elif r == 7: age = 'Very Old'
            elif r == 8: age = 'Ancient'
            
            self.hp = self.hit_die[0] * r
            
            if dragon_size != 'Average':
                self.name = '{} {} {}'.format(age,dragon_size,self.name)
            else:
                self.name = '{} {}'.format(age,self.name)
    
        
        self.c_type = c_type
        if not type(c_type) == DragonType:
            self.hp, self.hit_die = rollHP(self.c_type.hit_die)
        self.intelligence = determineIntelligence(self.c_type.iq)
        self.xp = determineXP(self)
        

        
    def __str__(self):
        output = '{}HP {} {}XP'.format(self.hp, self.name, self.xp)
        return output
    
def determineIntelligence(iq):
    if iq == 'Non': intellect = 0
    elif iq == 'Animal': intellect = 1
    elif iq == 'Semi': intellect = randint(2,4)
    elif iq == 'Low': intellect = randint(5,7)
    elif iq == 'Average': intellect = randint(8,10)
    elif iq == 'Very': intellect = randint(11,12)
    elif iq == 'High': intellect = randint(13,14)
    elif iq == 'Exceptional': intellect = randint(15,16)
    elif iq == 'Genuis': intellect = randint(17,18)
    elif iq == 'Supra-Genius': intellect = randint(19,20)
    elif iq == 'Godlike': intellect = 21
    
    return intellect
    
creature_types = [
CreatureType('Aerial Servant',
    num = (1,1),
    ac = 3,
    move = Move(24,24),
    lair = 0.0,
    hd = (16,16,0),
    attacks = [(8,4,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Surprise on 1-4','Hit only by magic weapons','Invisible'],
    exceptional = ['Powerful grasp']
),
CreatureType('Anhkeg',
    num = (1,1),
    ac = 2,
    move = Move(12,burrow=6),
    lair = 0.15,
    hd = (3,8,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Bite applies enzyme that does 1d4/turn',
    'If severely threatened, spits enzyme 30\' once/6hrs 8d4 half if save v poison'],
    exceptional = [],
    notes = 'Tend to wait burrowed 5-10ft for prey, Underside has AC 4'
),
CreatureType('Giant Ant',
    num = (1,100),
    ac = 3,
    move = Move(18),
    lair = 0.10,
    hd = (2,2,0),
    attacks = [(6,1,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = [],
    notes = 'Outside lair 10% chance of warriors (1 of 5)'+
            '\nIn lair double number rolled and add 1 warrior for each 5 and a queen'
),
CreatureType('Giant Warrior Ant',
    num = (1,1),
    ac = 3,
    move = Move(18),
    lair = 0.9,
    hd = (3,3,0),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'M',
    special = ['On hit, sting for 3d4 (1d4 if save v poison)'],
    exceptional = []
),
CreatureType('Giant Queen Ant',
    num = (1,1),
    ac = 3,
    move = Move(0),
    lair = 1.0,
    hd = (10,10,0),
    attacks = [],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = [],
    notes = 'Guarded by 5d10 workers and 5 warriors'+
            '\nWhen dead, other ants will be Confused 6 rds then flee the nest'
),
CreatureType('Ape (Gorilla)',
    num = (1,4),
    ac = 6,
    move = Move(12),
    lair = 0.0,
    hd = (4,4,1),
    attacks = [(3,1,0),(3,1,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'M',
    special = ['If both hands hit, grabs and rends for 1d6'],
    exceptional = [],
    notes = 'Not aggressive unless threatened'
),
CreatureType('Carnivorous Ape',
    num = (2,8),
    ac = 6,
    move = Move(12),
    lair = 0.10,
    hd = (5,5,0),
    attacks = [(4,1,0),(4,1,0),(8,1,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'L',
    special = ['If both hands hit, grabs and rends for 1d8','Surprised on 1'],
    exceptional = []
),    
CreatureType('Axe Beak',
    num = (1,6),
    ac = 6,
    move = Move(18),
    lair = 0.0,
    hd = (3,3,0),
    attacks = [(4,2,0),(3,1,0),(3,1,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Baboon',
    num = (10,40),
    ac = 7,
    move = Move(12),
    lair = 0.0,
    hd = (1,1,1),
    attacks = [(4,1,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = [],
    notes = 'Tribe led by 2d4 large males with +1 damage'+
            '\nHalf the tribe will be non-attacking young'+
            '\n90% likely to flee against determined resistance'
),
CreatureType('Large Baboon Leader',
    num = (2,8),
    ac = 7,
    move = Move(12),
    lair = 0.0,
    hd = (1,1,1),
    attacks = [(4,1,1)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = []
),
CreatureType('Badger',
    num = (2,5),
    ac = 4,
    move = Move(6,burrow=3),
    lair = 0.0,
    hd = (1,1,2),
    attacks = [(2,1,0),(2,1,0),(3,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = [],
    notes = 'If more than 1, mated pair with young'
),
CreatureType('Giant Badger',
    num = (2,5),
    ac = 4,
    move = Move(12,burrow=6),
    lair = 0.0,
    hd = (3,3,0),
    attacks = [(3,1,0),(3,1,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = [],
    notes = 'If more than 1, mated pair with young'
),
CreatureType('Baluchitherium',
    num = (1,3),
    ac = 5,
    move = Move(12),
    lair = 0.0,
    hd = (14,14,0),
    attacks = [(4,5,0),(4,5,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = [],
    notes = 'If 3 encountered, mated pair with young'
),    
CreatureType('Barracuda',
    num = (2,12),
    ac = 6,
    move = Move(ground=0,water=30),
    lair = 0.0,
    hd = (1,3,0),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = [],
    notes = 'Attack anything injured, helpless or small'
),  
CreatureType('Basilisk',
    num = (1,4),
    ac = 4,
    move = Move(6),
    lair = 0.4,
    hd = (6,6,1),
    attacks = [(10,1,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = ['Gaze turns to stone'],
    notes = 'Can see into astral (gaze kills) and ethereal (gaze into ethereal stone) planes. '+
            '\nReflecting the gaze will petrify the basilisk.'
),  
CreatureType('Black Bear',
    num = (1,3),
    ac = 7,
    move = Move(12),
    lair = 0.0,
    hd = (3,3,3),
    attacks = [(3,1,0),(3,1,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'M',
    special = ['Paw hits 18+ hug for 2d4 additional','Fight for 1d4 rds when at 0 to -8 HP'],
    exceptional = [],
    notes = 'Generally non-aggressive'
),
CreatureType('Brown Grizzly Bear',
    num = (1,6),
    ac = 6,
    move = Move(12),
    lair = 0.0,
    hd = (5,5,5),
    attacks = [(6,1,0),(6,1,0),(8,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Paw hits 18+ hug for 2d6 additional','Fight for 1d4 rds when at 0 to -8 HP'],
    exceptional = []
),
CreatureType('Cave Bear',
    num = (1,2),
    ac = 6,
    move = Move(12),
    lair = 0.0,
    hd = (6,6,6),
    attacks = [(8,1,0),(8,1,0),(12,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Paw hits 18+ hug for 2d8 additional','Fight for 1d4 rds when at 0 to -8 HP'],
    exceptional = []
),      
CreatureType('Giant Beaver',
    num = (10,40),
    ac = 6,
    move = Move(6,water=12),
    lair = 0.8,
    hd = (4,4,0),
    attacks = [(4,4,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = [],
    notes = 'Live in castle-like dam in river. Will alarm if dam is threatened'
),
CreatureType('Giant Bombardier Beetle',
    num = (3,12),
    ac = 4,
    move = Move(9),
    lair = 0.0,
    hd = (12,12,0),
    attacks = [(6,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'M',
    special = ['Creatures eaten cannot be revived'],
    exceptional = ['50% chance to fire 8 cubic ft cloud of vapor 3d4' +
                   'cloud can 20% stun 2d4 rds and 20% deafen 2d6 for creatures not stunned'],
    notes = 'Cloud can be fired every 3rd rd, but no more than twice in eight hours'
),   
CreatureType('Giant Boring Beetle',
    num = (3,18),
    ac = 3,
    move = Move(6),
    lair = 0.4,
    hd = (5,5,0),
    attacks = [(4,5,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'L',
    special = ['Creatures eaten may not be revived'],
    exceptional = [],
    notes = 'Groups develop conciousness approximating humans'
), 
CreatureType('Giant Fire Beetle',
    num = (3,12),
    ac = 4,
    move = Move(12),
    lair = 0.0,
    hd = (1,1,2),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = ['Creatures eaten may not be revived'],
    exceptional = [],
    notes = 'Have glands at eyes and back that illuminate 10ft'
),
CreatureType('Giant Rhinocerous Beetle',
    num = (1,6),
    ac = 2,
    move = Move(6),
    lair = 0.0,
    hd = (12,12,0),
    attacks = [(6,3,0),(8,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Giant Stag Beetle',
    num = (2,12),
    ac = 3,
    move = Move(6),
    lair = 0.0,
    hd = (7,7,0),
    attacks = [(4,4,0),(10,1,0),(10,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Giant Water Beetle',
    num = (1,12),
    ac = 3,
    move = Move(3,water=12),
    lair = 0.0,
    hd = (4,4,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),  
CreatureType('Beholder',
    num = (1,1),
    ac = 0,
    move = Move(0,3),
    lair = 0.8,
    hd = (0,0,75),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Exceptional',
    align = 'LE',
    size = 'L',
    special = [],
    exceptional = ['Anti-Magic Ray 14" Eye','Charm Person Central Eye','Charm Monster Eye','Sleep Eye','Telekinesis 2500gp Eye',
                   'Flesh-stone Ray 2" Eye', 'Disintegrate Ray 2" Eye','Fear (wand) Eye',
                   'Slow Eye', 'Serious Wounds 5" Eye','Death Ray 4" Eye'],
    notes = 'Has 10 Eyestalks AC 7, Eyes AC 2, Damage to stalks does not hurt body grow back in 1 week'+
            '\nEyes die after 25HP, Body dies when main eye takes 25HP or body takes 50HP, eyestalks 10HP'+
            '\nCan use central eye plus 1d4 others for targets 90 degrees in front'+
            '\nDouble for 180 degrees, triple for 270, quadruple for 360. Above, all but central'
),
CreatureType('Black Pudding',
    num = (1,1),
    ac = 6,
    move = Move(6),
    lair = 0.0,
    hd = (10,10,0),
    attacks = [(8,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'M',
    special = ['Cold immune'],
    exceptional = ['Eat away at armor before doing damage'+
            '\n2inch/rd wood, chainmail in 1rd, plate in 2rd plus 1rd per +1 magic protect',
            'Breaks into multiple creatures each time struck or shocked'],
    notes = 'Can flow through 1 inch cracks'
),
CreatureType('Blink Dog',
    num = (4,16),
    ac = 5,
    move = Move(12),
    lair = 0.2,
    hd = (4,4,0),
    attacks = [(6,1,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'LG',
    size = 'M',
    special = [],
    exceptional = ['Can teleport (blink) before attack,'+
        '\nRoll 12 1:front 2:left(shield) 3:right 4-12:behind'],
    notes = 'When seriously threatened or more than 25% dead, will teleport permanently away'+
            '\nHate displacer beasts and will always attack them'
),
CreatureType('Wild Boar',
    num = (1,12),
    ac = 7,
    move = Move(15),
    lair = 0.0,
    hd = (3,3,3),
    attacks = [(4,3,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'M',
    special = ['Fight for d4+1 rds from 0 to -6 HP'],
    exceptional = [],
    notes = 'When more than 1 encountered, the rest are sows and young at a 1:4 ratio'
),
CreatureType('Wild Boar Sow',
    num = (1,1),
    ac = 7,
    move = Move(15),
    lair = 0.0,
    hd = (3,3,0),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = []
),
CreatureType('Giant Boar',
    num = (2,8),
    ac = 6,
    move = Move(12),
    lair = 0.0,
    hd = (7,7,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'L',
    special = ['Fights for d4 rds at 0 to -10HP'],
    exceptional = [],
    notes = '25% that 1-4 will be young'
),
CreatureType('Young Giant Boar',
    num = (1,4),
    ac = 6,
    move = Move(12),
    lair = 0.0,
    hd = (2,6,0),
    attacks = [(6,1,1)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = []
),
CreatureType('Warthog',
    num = (1,6),
    ac = 7,
    move = Move(12),
    lair = 0.0,
    hd = (3,3,0),
    attacks = [(4,2,0),(4,2,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'M',
    special = ['Fights for 1-2 rds at 0 to -5 HP'],
    exceptional = [],
    notes = 'When more than 2 encountered, the rest are young.'
),
CreatureType('Young Warthog',
    num = (1,1),
    ac = 7,
    move = Move(12),
    lair = 0.0,
    hd = (1,2,0),
    attacks = [(4,1,0),(4,1,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = []
),
CreatureType('Brain Mole',
    num = (1,3),
    ac = 9,
    move = Move(1),
    lair = 0.0,
    hd = (0,0,1),
    attacks = [],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = ['121 pt psionic mind thrust',
            '20%/rd chance of permanent insanity when burrowing non-psionics'],
    notes = 'Only attacks when psionics or psionic-like spells used within 30ft'+
            '\n will immediately stop when psionics halt'
),
CreatureType('Brownie',
    num = (4,16),
    ac = 3,
    move = Move(12),
    lair = 0.2,
    hd = (1,1,-4),
    attacks = [(3,1,0)],
    m_resist = 0.0,
    iq = 'High',
    align = 'LG',
    size = 'S',
    special = ['Prot evil 1/day','Ventriloquism 1/day','Dancing Lights 1/day',
            'Mirror Image (3 images) 1/day','Continual Light 1/day','Can blend to invisible'],
    exceptional = ['Save as 9th level cleric','Confusion 1/day','Dimension Door 1/day'],
    notes = '50% likely to help LG characters. Can repair wood,leather,metal easily.'
),
CreatureType('Buffalo',
    num = (4,24),
    ac = 7,
    move = Move(15),
    lair = 0.0,
    hd = (5,5,0),
    attacks = [(8,1,0),(8,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Charge for 3d6 impact, 1d4 trample; must be 40ft away'],
    exceptional = [],
    notes = '50% are non-aggresive and will flee when threatened'
),
CreatureType('Bugbear',
    num = (6,36),
    ac = 5,
    move = Move(9),
    lair = 0.25,
    hd = (3,3,1),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'L',
    special = ['Surprise on a 1-3','Often throw spears 4", under 2" as medium range'],
    exceptional = [],
    notes = 'Speak own tongue, alignment, goblin and hobgoblin. Carry swords, morning stars, spears.'+
        '\nIf 12 or more encountered, there will be a leader. If 24 or more, a chief.'+
        '\nIn a lair, there will always be a chief, leader and an additional 50% female and 50% young'+
        '\nIn life or death situations, females fight as hobgoblins, young as kobolds.' 
),
CreatureType('Bugbear Leader',
    num = (1,1),
    ac = 4,
    move = Move(9),
    lair = 0.0,
    hd = (4,4,1),
    attacks = [(4,2,1)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'CE',
    size = 'L',
    special = [],
    exceptional = [],
    notes = '+1 damage with weapons'
),
CreatureType('Bugbear Chief',
    num = (1,1),
    ac = 3,
    move = Move(9),
    lair = 0.0,
    hd = (4,4,2),
    attacks = [(4,2,2)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'CE',
    size = 'L',
    special = [],
    exceptional = [],
    notes = '+2 damage with weapons'
),
CreatureType('Bulette',
    num = (1,2),
    ac = -2,
    move = Move(14,burrow=3),
    lair = 0.0,
    hd = (6,11,0),
    attacks = [(12,4,0),(6,3,0),(6,3,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'L',
    special = ['Can jump 8ft in the air and attack with all 4 feet'],
    exceptional = [],
    notes = 'Favorite food is halfling. Don\'t eat elf or dwarf. AC 6 underside. Eyes AC 4'
),
CreatureType('Bull',
    num = (1,20),
    ac = 7,
    move = Move(15),
    lair = 0.0,
    hd = (4,4,0),
    attacks = [(6,1,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Charge from 30ft+ for 3d4 impact and 1d4 trample'],
    exceptional = [],
    notes = '75% likely to attack those within 8"'
),
CreatureType('Wild Camel',
    num = (1,12),
    ac = 7,
    move = Move(21),
    lair = 0.0,
    hd = (3,3,0),
    attacks = [(4,1,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'L',
    special = ['50% chance to spit, has 25% chance to blind 1-3 rds'],
    exceptional = [],
    notes = 'Horses dislike the odor of camels.'
),
CreatureType('Carrion Crawler',
    num = (1,6),
    ac = 7,
    move = Move(12),
    lair = 0.5,
    hd = (3,3,1),
    attacks = [(1,1,0),(1,1,0),(1,1,0),(1,1,0),(1,1,0),(1,1,0),(1,1,0),(1,1,0)],
    m_resist = 0.0,
    iq = '',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Paralyzes on hit','Eight paralyzing attacks'],
    notes = 'Head is AC 3'
),
CreatureType('Catoblepas',
    num = (1,3),
    ac = 7,
    move = Move(6),
    lair = 0.6,
    hd = (6,6,2),
    attacks = [(6,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Tail hit has 75% chance to stun for d10 rds -5% per level over 1',
                'Gaze as death ray 6", die without save 25% chance to use per round'],
    notes = 'If tracking moving target, gaze chance is 10%. If gaze doesn\'t meet eyes, save vs. death'
),
CreatureType('Wild Cattle',
    num = (20,200),
    ac = 7,
    move = Move(15),
    lair = 0.0,
    hd = (1,4,0),
    attacks = [(4,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Stampede for d4 trample. If no cover, roll 2d4 for each party member for number trampled by.'],
    exceptional = [],
    notes = 'Flee 75%, else charge. Will be accompanied by bulls.'
),
CreatureType('Centaur',
    num = (4,24),
    ac = 5,
    move = Move(18),
    lair = 0.05,
    hd = (4,4,0),
    attacks = [(6,1,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'NG',
    size = 'L',
    special = [],
    exceptional = [],
    notes = '50% carry oaken clubs (morning star), 25% composite long bows 10-30 arrows'+
        '\n25% leaders AC 4. In lair, d6 additional males, females twice males and 5d6 young.'+
        '\nFemales and young will only fight under extreme danger, using hooves.'+
        '\n90% likely to pay treasure for safety of young and females'+
        '\nSpeak centaur and alignment. Unfriendly towards humans, dwarves.'+
        '\nTolerate gnomes, halfling. Friendly towards elves.'
),
CreatureType('Giant Centipede',
    num = (2,24),
    ac = 9,
    move = Move(15),
    lair = 0.0,
    hd = (1,1,-6),
    attacks = [(1,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = ['Weak poison (+4 to save)'],
    exceptional = [],
    notes = 'Worse saves -1'
),
CreatureType('Cerebral Parasite',
    num = (3,12),
    ac = 10,
    move = Move(0),
    lair = 0.0,
    hd = (0,0,0),
    attacks = [],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = ['Only removed by Cure Disease',
        'Drain 1 psionic energy each on inital attack and per ability use',
        'Reproduce for each 6 energy drained'],
    exceptional = [],
    notes = 'Can only be detected by psionic aura check.'
),
CreatureType('Chimera',
    num = (1,4),
    ac = 5,
    move = Move(9,18),
    lair = 0.4,
    hd = (9,9,0),
    attacks = [(3,1,0),(3,1,0),(4,1,0),(4,1,0),(4,2,0),(4,3,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = ['50% breathe fire 5" 3d8 half if save.'],
    notes = 'Goat hind AC 6, Dragon wings AC 2. Speak limited red dragon'
),
CreatureType('Cockatrice',
    num = (1,6),
    ac = 6,
    move = Move(6,18),
    lair = 0.3,
    hd = (5,5,0),
    attacks = [(3,1,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = ['Hits turn flesh to stone'],
    notes = 'Exist simultaneously in prime, astral and ethereal planes.'
),
CreatureType('Couatl',
    num = (1,4),
    ac = 5,
    move = Move(6,18),
    lair = 0.1,
    hd = (9,9,0),
    attacks = [(3,1,0),(4,2,0)],
    m_resist = 0.0,
    iq = 'Genius',
    align = 'LG',
    size = 'M',
    special = ['Can polymorph self','May constrict on hit for 2d4 each round'],
    exceptional = ['Use magic as 5th Magic-User and/or 7th Cleric',
                'Use psionics 2 major, 4 minor','Poisonous bite'],
    notes = 'Speak common, and most serpent and avian languages. Rarely interfere with humans.'+
            '45% magic user, 35% cleric, 20% both.'
),
CreatureType('Giant Crab',
    num = (2,12),
    ac = 3,
    move = Move(9,water=9),
    lair = 0.0,
    hd = (3,3,0),
    attacks = [(4,2,0),(4,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Surprise on a 1-4'],
    exceptional = []
),
CreatureType('Giant Crayfish',
    num = (1,4),
    ac = 4,
    move = Move(6,water=12),
    lair = 0.0,
    hd = (4,4,4),
    attacks = [(6,2,0),(6,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Surprise on 1-3'],
    exceptional = []
),
CreatureType('Crocodile',
    num = (3,24),
    ac = 5,
    move = Move(6,water=12),
    lair = 0.0,
    hd = (3,3,0),
    attacks = [(4,2,0),(12,1,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'L',
    special = ['Surprise on 1-3'],
    exceptional = [],
    notes = '50% movement in cold'
),
CreatureType('Giant Crocodile',
    num = (1,12),
    ac = 4,
    move = Move(6,water=12),
    lair = 0.0,
    hd = (7,7,0),
    attacks = [(6,3,0),(10,2,0)],
    m_resist = 0.0,
    iq = 'Animal',
    align = 'NN',
    size = 'L',
    special = ['Surprise on 1-3'],
    exceptional = ['50% movement in cold']
),
CreatureType('Demogorgon, Prince of Demons',
    num = (1,1),
    ac = -8,
    move = Move(15),
    lair = 0.5,
    hd = (0,0,200),
    attacks = [(6,1,1),(6,1,0),(6,1,0)],
    m_resist = 0.95,
    iq = 'Supra-Genius',
    align = 'CE',
    size = 'L',
    special = ['Detect Magic', 'Read Magic', 'Read Languages', 'Detect Invisible Objects',
        'ESP','Clairvoyance','Clairaudience','Water Breathe','Sticks to Snakes',
        'Infravision','Takes 50% cold damage','Takes 50% electric damage',
        'Takes 50% fire damage','Takes 50% gas damage'],
    exceptional = ['+2 weapon required to hit',
        'Gaze with both heads hypnotizes 10-100 <4HD, 5-40 <7HD, 3-24 <10HD,'+
        '\n  2-12<13HD, 1-4 13+HD automatically. 15+HD may save vs magic.'+
        '\n  Lasts 1 turn and follow all but self-destruction,'+
        '\n  and will tend to believe or carry out commands for another 1-6 turns',
        'Left head gaze has Rod of Beguiling effect (save vs magic)',
        'Right head causes insanity for 1 to 6 turns (save vs magic)',
        'Tail strikes as whip-like flail and drains 1-4 levels',
        'Tentacles subject lesser (esp. prime material) creatures to rot.'+
        '\n  Limb useless in 6 rds, falls off in another 6 rds'+
        '\n  Body permanently loses 25%HP in 6 rds, cumulative per hit'+
        '\n  Cure disease within 6rds allows limb to heal in 1-4 weeks, body restored instantly.',
        'Continual Darkness',
        'Charm Person',
        'Create Illusion (as wand)',
        'Cause fear (as wand)',
        'Levitate (as 16th level MU)',
        'Dispel Magic',
        'Suggest',
        'Polymorph Self',
        'Wall of Ice',
        'Charm Monster',
        'Telekinesis 7000g.p. (with each head)',
        'Feeblemind 1/day',
        'Project Image',
        'Power word: stun 1/day',
        'Use any Symbol 1/day',
        'Gate demons 85% success, 50% Type I-IV, 50% Type V or VI',
        'Teleportation (no error)',
        'Magic jar 1/day with demon amulet'
        ],
    notes = 'Hateful rivalry with Orcus. Has a demon amulet, but doesn\t need to be near it.'
),
CreatureType('Jubilex, The Faceless Lord',
    num = (1,1),
    ac = -7,
    move = Move(3),
    lair = 0.6,
    hd = (0,0,88),
    attacks = [(4,10,0)],
    m_resist = 0.65,
    iq = 'Genius',
    align = 'CE',
    size = 'L',
    special = ['Detect invisible','Locate Object','ESP',
        'Project Image','Putrify food and water',
        'Spew slime 1/turn 15ft range 3 cubic ft (effects of ochre jelly and green slime)',
        'Takes 50% cold damage','Takes 50% electric damage','Takes 50% fire damage',
        'Takes 50% gas damage','Infravision'],
    exceptional = ['+2 required to hit','Circle of Darkness 15\'',
        'Fear (as wand)',
        'Circle of Cold 10\' radius',
        'Regen 2HP/rd',
        'Fly', 'Dispel Magic', 'Invisibility 10\' radius',
        'Charm monster', 'Hold monster', 'Telekinesis 15000g.p.',
        'Phase door','Cause disease','Speak unholy word 1/day',
        'Gate 70% success Type I-IV Demons',
        'Magic jar 1/day',
        'Teleport (no error)'],
        
    notes = 'In lair has 1-4 green slime, 2-8 ochre jelly, 1-4 gray ooze, 1-4 black pudding'+
        '\n  Shunned by other creatures and demons. Carries his demon amulet.'
),
CreatureType('Manes (Sub-Demon)',
    num = (4,16),
    ac = 7,
    move = Move(3),
    lair = 0.0,
    hd = (1,1,0),
    attacks = [(2,1,0),(2,1,0),(4,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'CE',
    size = 'S',
    special = ['+1 required to hit','50% cold damage','50% fire damage',
            '50% gas damage','50% electric damage','Infravision'],
    exceptional = [],
    notes = 'Treated as undead vs spells. Can be sent by lords or princes to material plane for 1 day'+
        '\nDeath turns them into stinking vapor cloud (return in 1 day)'
),
CreatureType('Orcus, Prince of the Undead',
    num = (1,1),
    ac = -6,
    move = Move(9,air=18),
    lair = 0.5,
    hd = (0,0,120),
    attacks = [(6,2,1),(4,2,0)],
    m_resist = 0.85,
    iq = 'Supra-Genius',
    align = 'CE',
    size = 'L',
    special = ['50% cold damage','50% fire damage','50% electric damage',
        '50% gas damage','Detect Magic','Read magic','Read languages',
        'Detect invisible objects','ESP','Clairvoyance','Clairaudience',
        'Project Image','Speak with Dead (as 20th cleric)','Infravision'],
    exceptional = ['+3 required to hit','+6 hit and +8 damage with weapons',
        'Poison sting tail (-4 to save)',
        'Continual Darkness',
        'Charm person',
        'Create Illusion (as wand)',
        'Cause Fear (as wand)',
        'Cause Pyrotechnics',
        'Dispel Magic',
        'Lightning Bolt (12 die)',
        'Suggest',
        'Polymorph Self',
        'Wall of Fire',
        'Telekinesis 12000 g.p.',
        'Animate Dead (as 19th MU)',
        'Feeblemind 1/day',
        'Use any symbol 1/day',
        'Polymorph any object',
        'Shape change',
        'Time stop 1/day',
        'Gate Demons 80% success 50% Type I-IV 50% V-VI',
        'Teleport (no error)',
        'Summon Undead (d4 1:4-48 skeletons, 2:4-32 zombies, 3:4-24 shadows, 4:2-8 vampires',
        'Holds the artifact Orcus\' Wand, which kills any lower creature on touch']
),
CreatureType('Succubus',
    num = (1,1),
    ac = 0,
    move = Move(12,air=18),
    lair = 0.05,
    hd = (6,6,0),
    attacks = [(3,1,0),(3,1,0)],
    m_resist = 0.7,
    iq = 'Exceptional',
    align = 'CE',
    size = 'M',
    special = ['50% cold damage','50% fire damage','50% electric damage','50% gas damage',
        'Cause darkness 5ft radius','+1 required to hit',
        'ESP','Clairaudience','Infravision'],
    exceptional = ['Teleport (no error)', 'Kiss drains 1 energy level',
        'Become ethereal (as using oil)','Charm person',
        'Suggestion (as spell)','Shape change (humanoid)',
        'Gate Demon 40% success Type IV (70%) Type VI (25%) Lord or Prince (5%)']
),
CreatureType('Type I Demon (Vrock)',
    num = (1,6),
    ac = 0,
    move = Move(12,air=18),
    lair = 0.05,
    hd = (8,8,0),
    attacks = [(4,1,0),(4,1,0),(8,1,0),(8,1,0),(6,1,0)],
    m_resist = 0.5,
    iq = 'Low',
    align = 'CE',
    size = 'L',
    special = ['50% cold damage','50% fire damage','50% electric damage','50% gas damage',
        'Detect invisible objects','Infravision',
        'Gate Demon (10% success) Type I',
        'Cause Darkness'],
    exceptional = ['Telekinesis 2000g.p.','Teleport (no error)'],
    notes = 'Will fight Type II Demon for any reason'
),
CreatureType('Type II Demon (Hezrou)',
    num = (1,6),
    ac = -2,
    move = Move(6,air=12),
    lair = 0.1,
    hd = (9,9,0),
    attacks = [(3,1,0),(3,1,0),(4,4,0)],
    m_resist = 0.55,
    iq = 'Low',
    align = 'CE',
    size = 'L',
    special = ['50% cold damage','50% fire damage','50% electric damage','50% gas damage',
        'Infravision','Cause Darkness 15ft radius',
        'Detect invisible objects'],
    exceptional = ['Teleport (no error)',
        'Cause fear (as wand)',
        'Levitate (as 8th MU)',
        'Telekinesis 3000g.p.',
        'Gate Type II Demon 20% success'],
    notes = 'Will fight Type I Demon for any reason'
),
CreatureType('Type III Demon (Glabrezu)',
    num = (1,6),
    ac = -4,
    move = Move(9),
    lair = 0.15,
    hd = (10,10,0),
    attacks = [(6,2,0),(6,2,0),(3,1,0),(3,1,0),(4,1,1)],
    m_resist = 0.6,
    iq = 'Average',
    align = 'CE',
    size = 'L',
    special = ['50% cold damage','50% fire damage','50% electric damage','50% gas damage',
        'Infravision', 'Cause Darkness 10ft radius'],
    exceptional = ['Teleport (no error)',
        'Fear (as wand)','Levitate as 10th MU','Cause Pyrotechnics','Polymorph Self',
        'Telekinesis 4000g.p.','Gate Demon I-III 30% success']
),
CreatureType('Type IV Demon (Nalfeshnee)',
    num = (1,6),
    ac = -1,
    move = Move(9,air=12),
    lair = 0.15,
    hd = (11,11,0),
    attacks = [(4,1,0),(4,1,0),(4,2,0)],
    m_resist = 0.65,
    iq = 'Very',
    align = 'CE',
    size = 'L',
    special = ['50% cold damage','50% fire damage','50% electric damage','50% gas damage',
        'Infravision', 'Cause Darkness 10ft radius','+1 required to hit',
        'Detect magic','Read languages'],
    exceptional = ['Create Illusion (as wand)','Cause fear (as wand)',
        'Levitate as 12th MU','Dispel Magic','Polymorph Self',
        'Telekinesis 5000g.p.','Use symbol of fear or discord',
        'Gate I-IV Demon 60% success',
        'Teleport (no error)'],
    notes = 'Some have names, if spoken 90% chance of listening to offers of rewards for small service'
),
CreatureType('Type V Demon (Marilith)',
    num = (1,6),
    ac = -7,
    move = Move(12),
    lair = 0.1,
    hd = (7,7,7),
    attacks = [(4,2,0),(4,2,0),(4,2,0),(4,2,0),(4,2,0),(4,2,0)],
    m_resist = 0.8,
    iq = 'High',
    align = 'CE',
    size = 'L',
    special = ['50% cold damage','50% fire damage','50% electric damage','50% gas damage',
        'Infravision', 'Cause Darkness 5ft radius','+1 required to hit',
        'Tail constrict','Read languages'],
    exceptional = ['Charm person','Levitate (as 11th MU)',
        'Cause pyrotechnics','Polymorph self',
        'Demon gate 50% success (30% I, 25% II, 15% III, 15% IV, 10% VI, lord or prince 5%',
        'Teleport (no error)'],
    notes = 'May use weapons in their six hands (usually sword or battle axe). Have names'
),
CreatureType('Type VI Demon (Balor)',
    num = (1,6),
    ac = -2,
    move = Move(6,air=15),
    lair = 0.2,
    hd = (8,8,8),
    attacks = [(12,1,1)],
    m_resist = 0.75,
    iq = 'High',
    align = 'CE',
    size = 'L',
    special = ['50% cold damage','50% fire damage','50% electric damage','50% gas damage',
        'Infravision', 'Cause Darkness 10ft radius','+1 required to hit',
        'Detect magic','Read magic','Read languages','Detect invisible objects'],
    exceptional = ['1-4 on d6 chance each round of immolate and use whip causing'+
        '\n  4-24 or 3-18 or 2-12 damage if victim pulled into flames depending on size',
        'Cause fear (as wand)','Pyrotechnics','Dispel Magic','Suggestion',
        'Telekinesis 6000g.p.','Use symbol of fear, discord, sleep or stunning',
        'Gate Demon 70% success type III 80% or type IV 20%'],
    notes = 'Only 6 exist, 2 large, 2 medium, 2 small. Slightly less chaotic than others'
),
CreatureType('Yeenoghu, Demon Lord of Gnolls',
    num = (1,1),
    ac = -5,
    move = Move(18),
    lair = 0.35,
    hd = (0,0,100),
    attacks = [(6,3,0)],
    m_resist = 0.8,
    iq = 'Exceptional',
    align = 'CE',
    size = 'L',
    special = ['50% cold damage','50% fire damage','50% electric damage','50% gas damage',
        'Infravision', 'Cause Darkness 10ft radius','+1 required to hit',
        'Gate demons 1/day 80% chance for 2-5 Type I'],
    exceptional = ['Can summon 6-66 gnolls in one turn',
        'Summon 6-16 ghouls in one turn',
        '2nd spike of flail if hit paralyze (save v wands)',
        '3rd spike of flail if hit confusion (save v magic)',
        'Magic Missile 3/day 6 missiles/cast 2-8 damage +2 to hit',
        'Invisibility',
        'Fly',
        'Hold Person',
        'Dispel Magic (as 20th MU)',
        'Suggestion',
        'Polymorph Self',
        'Fear (as wand)',
        'Teleport',
        'Telekinesis 10000g.p.',
        'Mass charm'],
    notes = 'Normally accompanied by 66 strongest gnolls (14-16HP). Flail attacks 3 times at once'+
        '\n  Carries his demon amulet'
),
CreatureType('Asmodeus (Arch-Devil)',
    num = (1,1),
    ac = -7,
    move = Move(12,air=24),
    lair = 0.9,
    hd = (0,0,199),
    attacks = [(6,2,2)],
    m_resist = 0.9,
    iq = 'Supra-Genius',
    align = 'LE',
    size = 'L',
    special = ['50% cold damage','50% gas damage','Strength of Storm Giant',
        'Produce Flame','Continual Light','Read languages','Read Magic',
        'Detect Invisible','Locate Object','Infravision','Know Alignment'],
    
    exceptional = ['+3 required to hit','Fire immune',
        
        'Pyrotechnics','Wall of Fire','Ice Storm','Wall of Ice',
        'Invisibility','Dispel Magic','Hold Person','Hold Monster',
        'Shape Change','Beguile','Rulership','Mass Charm','Geas',
        'Restoration','Raise dead fully','Fulfill another\'s wish',
        'Symbol of Pain 1/day',
        'Symbol of Insanity 1/day',
        'Symbol of hopelessness 1/day (save v magic or submit to his will)',
        'Unholy word 1/day',
        'Fear gaze',
        'Fear and weakness gaze',
        'Chill gaze (50% move slow and -5 on all dice rolls)',
        'Summon 2 lesser or 1 greater devil',
        'Carries Rod of Pure Ruby (Rod of Absorption) that may:'+
        '\n  Cone of Frost, Jet of Acid, Bolt of Lighting (all as dragon breath)',
        'Charm Person',
        'Suggestion',
        'Illusion', 'Teleport (no error)','Animate Dead'
        ]
),
CreatureType('Baalzebul (Arch-Devil)',
    num = (1,1),
    ac = -5,
    move = Move(9,air=24),
    lair = 0.8,
    hd = (0,0,166),
    attacks = [(6,2,0)],
    m_resist = 0.85,
    iq = 'Genuis',
    align = 'LE',
    size = 'L',
    special = ['50% cold damage','50% gas damage','Infravision',
        'Know Alignment','Detect Invisible','Locate Object',
        'Read Languages','Read Magic','Continual Light'],
    exceptional = ['+3 required to hit','Fire Immune',
        'Pyrotechnics','Wall of Fire','Invisibility',
        'Dispel Magic','Shape Change','Beguile','Rulership',
        'Hold Person','Charm Monster','Geas','Restoration',
        'Raise Dead (fully)','Fulfill another\'s wish',
        'Symbol of Pain 1/day','Symbol of Insanity 1/day',
        'Unholy Word 1/day','Summon 1-4 horned devils',
        'Fear and weakness gaze',
        'Charm Person','Suggestion','Illusion',
        'Animate Dead','Teleport (no error)']
),
CreatureType('Barbed Devil',
    num = (1,12),
    ac = 0,
    move = Move(12),
    lair = 0.5,
    hd = (8,8,0),
    attacks = [(4,2,0),(4,2,0),(4,3,0)],
    m_resist = 0.35,
    iq = 'Very',
    align = 'LE',
    size = 'M',
    special = ['Never surprised','50% cold damage','50% gas damage','Infravision',
        'Know Alignment','Produce Flame'],
    exceptional = ['Fear on strike','Fire Immune',
        'Pyrotechnics','Hold Person','Summon Barbed Devil 30% chance',
        'Charm Person','Suggestion','Illusion',
        'Animate Dead','Teleport (no error)']
),
CreatureType('Bone Devil',
    num = (1,8),
    ac = -1,
    move = Move(15),
    lair = 0.55,
    hd = (9,9,0),
    attacks = [(4,3,0)],
    m_resist = 0.4,
    iq = 'Very',
    align = 'LE',
    size = 'L',
    special = ['Infravision','50% cold damage','50% gas damage','Know Alignment'],
    exceptional = ['Ultravision 60ft','Fire Immune',
        'Hit with hook 50% chance of being held',
        'Strikes held victims with tail for 2d4, save v poison or lose d4 STR 10rds',
        'Generate Fear 10ft radius',
        'Create Illusion',
        'Fly',
        'Become invisible',
        'Fear',
        'Summon Bone Devil 40% success',
        'Wall of Ice 1/day',
        'Charm Person','Suggestion','Illusion',
        'Animate Dead','Teleport (no error)']
),
CreatureType('Dispater (Arch-Devil)',
    num = (1,1),
    ac = -2,
    move = Move(15),
    lair = 0.8,
    hd = (0,0,144),
    attacks = [(6,4,0)],
    m_resist = 0.0,
    iq = 'Genius',
    align = 'LE',
    size = 'M',
    special = ['Infravision','50% cold damage','50% gas damage','Know Alignment',
        'Produce Flame','Light','Read Magic','Read Languages','Detect Invisible'],
    exceptional = ['Fire Immune','+2 required to hit',
        'Pyrotechnics','Wall of Fire',
        'Shape Change','Beguile','Geas','Restoration','Raise Dead Fully',
        'Fulfill Another\'s Wish',
        'Summon Devils 90% success (75% 1-3 erinyes, 25% pit fiend)',
        'Symbol of Pain 1/day',
        'Unholy Word 1/day',
        'Fear Gaze',
        'Chill Gaze',
        'Carries Rod of Rulership acting as double strength staff of striking',
        'Charm Person','Suggestion','Illusion',
        'Animate Dead','Teleport (no error)']
),
CreatureType('Erinyes',
    num = (1,16),
    ac = 2,
    move = Move(6,air=21),
    lair = 0.2,
    hd = (6,6,6),
    attacks = [(4,2,0)],
    m_resist = 0.3,
    iq = 'Average',
    align = 'LE',
    size = 'M',
    special = ['50% cold damage','50% gas damage','Know Alignment','Infravision',
        'Detect Invisible','Locate Object','Produce Flame'],
    exceptional = ['On hit save v poison or faint 1d6 rds',
        'Carry rope of entanglement to bind victims',
        'Fire immune','Charm Person','Suggestion','Illusion',
        'Animate Dead','Teleport (no error)',
        'Cause Fear','Invisibility','Polymorph Self',
        'Summon another Erinyes 25%']
),
CreatureType('Geryon (Arch-Devil)',
    num = (1,1),
    ac = -3,
    move = Move(3,air=18),
    lair = 0.7,
    hd = (0,0,133),
    attacks = [(6,3,0),(6,3,0),(4,2,0)],
    m_resist = 0.75,
    iq = 'Exceptional',
    align = 'LE',
    size = 'L',
    special = ['50% cold damage','50% gas damage','Know Alignment','Infravision',
        'Light','Read Languages','Read Magic','Detect Invisible','Locate Object'],
    exceptional = ['Fire immune','Charm Person','Suggestion','Illusion',
        'Animate Dead','Teleport (no error)',
        '+2 required to hit',
        'Poisonous tail -4 save v poison or die',
        'Ice Storm',
        'Wall of Ice',
        'Invisibility',
        'Shape Change',
        'Dispel Magic',
        'Beguile',
        'Geas',
        'Raise Dead Fully',
        'Fulfill Another\'s Wish',
        'Symbol of Pain 1/day',
        'Unholy Word 1/day',
        'Summon Devils 95% success (60% 1-2 bone devils, 40% ice devil)',
        'Fear gaze',
        'Carries Great Bull\'s Horn summon 5-20 minotaurs once/week']
),
CreatureType('Horned Devil (Malebranche)',
    num = (1,5),
    ac = -5,
    move = Move(9,air=18),
    lair = 0.55,
    hd = (5,5,5),
    attacks = [(4,1,0),(4,1,0),(4,1,1),(3,1,0)],
    m_resist = 0.5,
    iq = 'High',
    align = 'LE',
    size = 'L',
    special = ['50% cold damage','50% gas damage','Know Alignment','Infravision',
        'ESP','Detect Magic','Produce Flame','Tail attack causes bleed 1HP/turn'],
    exceptional = ['Fire immune','Charm Person','Suggestion','Illusion',
        'Animate Dead','Teleport (no error)',
        '+1 required to hit',
        'Continually exude Fear in 5ft radius',
        'Pyrotechnics','Summon Horned Devil 50% success',
        'Wall of Fire Triple Strength (3-24) 1/day'],
    notes = 'If armed, may carry fork (2-12 damage) or barbed whip (1-4 damage and rds stunned save v magic)'
),
CreatureType('Ice Devil',
    num = (1,4),
    ac = -4,
    move = Move(6),
    lair = 0.6,
    hd = (11,11,0),
    attacks = [(4,1,0),(4,1,0),(4,2,0),(4,3,0)],
    m_resist = 0.55,
    iq = 'High',
    align = 'LE',
    size = 'L',
    special = ['50% cold damage','50% gas damage','Know Alignment','Infravision',
        'Regenerate 1HP/rd'],
    exceptional = ['Fire immune','Charm Person','Suggestion','Illusion',
        'Animate Dead','Teleport (no error)',
        'Fly','Wall of Ice','Polymorph Self',
        'Gate Devils 60% success (2 bone 70%, ice devil 30%)',
        'Ice Storm 1/day',
        'Ultravision',
        'Always radiate Fear 10 ft radius (save v wand)'],
    notes = '25% carry spears (2-12) that cause cold (50% move slow save v paralyze)'+
        '\n  Grasp strength of 18/76'
),
CreatureType('Lemure',
    num = (5,30),
    ac = 7,
    move = Move(3),
    lair = 1.0,
    hd = (3,3,0),
    attacks = [(3,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'LE',
    size = 'M',
    special = ['Regenerate 1HP/rd','Can only be destroyed by holy water, holy sword,etc.',
        'Immune to sleep, charm, etc.','50% cold damage','50% gas damage','Infravision'],
    exceptional = ['Fire Immune']
),
CreatureType('Pit Fiend',
    num = (1,3),
    ac = -3,
    move = Move(6,air=15),
    lair = 0.65,
    hd = (13,13,0),
    attacks = [(4,1,4),(6,1,6)],
    m_resist = 0.65,
    iq = 'Exceptional',
    align = 'LE',
    size = 'L',
    special = ['Produce Flame','Detect Magic','Detect Invisible'],
    exceptional = ['Pyrotechnics','Wall of Fire',
        'Polymorph Self','Hold Person',
        'Gate 70% success (60% 1-3 barbed devils, 40% pit fiend)',
        'Symbol of Pain 1/day save v magic or -4 on hit rolls -2 DEX 2d10 rds',
        'Always shed fear in 20ft radius save v magic',
        'Regen 2HP/rd',
        'Tail strike holds and constricts for 2d4 per turn'],
    notes = 'Strength 18/00' 
),
CreatureType('Anatosaurus (Trachodon)',
    num = (2,12),
    ac = 5,
    move = Move(12),
    lair = 0.0,
    hd = (12,12,0),
    attacks = [(4,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = [],
    notes = 'Run from attacks when possible'
),
CreatureType('Ankylosaurus',
    num = (2,5),
    ac = 0,
    move = Move(6),
    lair = 0.0,
    hd = (9,9,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Antrodemus (Allosaurus)',
    num = (1,2),
    ac = 5,
    move = Move(15),
    lair = 0.0,
    hd = (15,15,0),
    attacks = [(4,1,0),(4,1,0),(4,6,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Apatosaurus (Brontosaurus)',
    num = (1,6),
    ac = 5,
    move = Move(6),
    lair = 0.0,
    hd = (30,30,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Trample for 4d10'],
    notes = 'Generally ignores smaller creatures, but tends to step on them'
),
CreatureType('Archelon Ischyras',
    num = (1,4),
    ac = 3,
    move = Move(3,water=15),
    lair = 0.0,
    hd = (7,7,0),
    attacks = [(4,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Brachiosaurus',
    num = (1,6),
    ac = 5,
    move = Move(6),
    lair = 0.0,
    hd = (36,36,0),
    attacks = [(4,5,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Trample for 8d10']
),
CreatureType('Camarasaurus',
    num = (2,8),
    ac = 6,
    move = Move(6),
    lair = 0.0,
    hd = (20,20,0),
    attacks = [(4,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Trample for 3d10']
),
CreatureType('Ceratosaurus',
    num = (1,4),
    ac = 5,
    move = Move(15),
    lair = 0.0,
    hd = (8,8,0),
    attacks = [(6,1,0),(6,1,0),(4,4,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Cetiosaurus',
    num = (1,4),
    ac = 6,
    move = Move(6),
    lair = 0.0,
    hd = (24,24,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Can trample for 4d10']
),
CreatureType('Dinichtys',
    num = (1,4),
    ac = 7,
    move = Move(0,water=21),
    lair = 0.0,
    hd = (10,10,0),
    attacks = [(4,5,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Swallow man-sized on 20 roll']
),
CreatureType('Diplodocus',
    num = (1,6),
    ac = 6,
    move = Move(6,water=6),
    lair = 0.0,
    hd = (24,24,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Trample for 3d10']
),
CreatureType('Elasmosaurus',
    num = (1,2),
    ac = 7,
    move = Move(15),
    lair = 0.0,
    hd = (15,15,0),
    attacks = [(6,4,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = [],
    notes = 'Highly aggressive'
),
CreatureType('Iguanadon',
    num = (3,18),
    ac = 4,
    move = Move(15),
    lair = 0.0,
    hd = (6,6,0),
    attacks = [(3,1,0),(3,1,0),(4,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Lambeosaurus',
    num = (2,16),
    ac = 6,
    move = Move(12),
    lair = 0.0,
    hd = (12,12,0),
    attacks = [(6,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Megalosaurus',
    num = (1,2),
    ac = 5,
    move = Move(12),
    lair = 0.0,
    hd = (12,12,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Monoclonius',
    num = (2,12),
    ac = 4,
    move = Move(6),
    lair = 0.0,
    hd = (8,8,0),
    attacks = [(8,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Charge for 2d8'],
    exceptional = [],
    notes = 'Head and neck AC 3'
),
CreatureType('Mosasaurus',
    num = (1,3),
    ac = 7,
    move = Move(3,water=15),
    lair = 0.0,
    hd = (12,12,0),
    attacks = [(8,4,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = []
),
CreatureType('Paleoscincus',
    num = (1,4),
    ac = -3,
    move = Move(3),
    lair = 0.0,
    hd = (9,9,0),
    attacks = [(6,2,0)],
    m_resist = 0.0,
    iq = '',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = [],
    notes = 'Predators inflict 3d12 trying to bite (extrapolate for player touches)'
),
CreatureType('Pentaceratops',
    num = (2,12),
    ac = 6,
    move = Move(9),
    lair = 0.0,
    hd = (12,12,0),
    attacks = [(6,1,0),(10,1,0),(10,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Charge for 2d10 trample'],
    exceptional = [],
    notes = 'Head is AC2'
),
CreatureType('Plateosaurus',
    num = (5,20),
    ac = 5,
    move = Move(12),
    lair = 0.0,
    hd = (8,8,0),
    attacks = [],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = [],
    notes = 'Panicky'
),
CreatureType('Plesiosaurus',
    num = (1,3),
    ac = 7,
    move = Move(15,water=15),
    lair = 0.0,
    hd = (20,20,0),
    attacks = [(4,5,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['In water, can also strike with flippers for 2d6 each'],
    exceptional = []
),
CreatureType('Pteranodon',
    num = (3,18),
    ac = 7,
    move = Move(3,air=15),
    lair = 0.0,
    hd = (3,3,3),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Can carry off prey 200 lbs'],
    exceptional = []
),
CreatureType('Stegosaurus',
    num = (2,8),
    ac = 2,
    move = Move(6),
    lair = 0.0,
    hd = (18,18,0),
    attacks = [(4,5,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = [],
    notes = '10% of the time, spike defense fails and AC is 5 for that attack'
),
CreatureType('Styracosaurus',
    num = (2,8),
    ac = 4,
    move = Move(6),
    lair = 0.0,
    hd = (10,10,0),
    attacks = [(8,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Charge trample for 2d8'],
    exceptional = [],
    notes = 'Aggresive herbivore, head is AC 2.'+
        '\n 50% chance that bites at rear are hit by 1-3 frills, doing 1d6 each'
),
CreatureType('Teratosaurus',
    num = (1,3),
    ac = 5,
    move = Move(18),
    lair = 0.0,
    hd = (10,10,0),
    attacks = [(3,1,0),(3,1,0),(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = [],
    notes = 'Carnivore'
),
CreatureType('Triceratops',
    num = (2,8),
    ac = 6,
    move = Move(9),
    lair = 0.0,
    hd = (16,16,0),
    attacks = [(8,1,0),(12,1,0),(12,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Charge trample for 2d12'],
    exceptional = [],
    notes = 'Head is AC 2, very territorial.'
),
CreatureType('Tyrannosaurus Rex',
    num = (1,2),
    ac = 5,
    move = Move(15),
    lair = 0.0,
    hd = (18,18,0),
    attacks = [(6,1,0),(6,1,0),(8,5,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Swallow man-sized creatures whole on 18+ roll']
),
CreatureType('Displacer Beast',
    num = (2,5),
    ac = 4,
    move = Move(15),
    lair = 0.25,
    hd = (6,6,0),
    attacks = [(4,2,0),(4,2,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Save as 12th level fighter +2 on rolls',
        'Opponents subtract 2 from their attack rolls due to displacement'],
    exceptional = [],
    notes = 'Hate Blink Dogs.'
),
CreatureType('Djinni',
    num = (1,1),
    ac = 4,
    move = Move(9,air=24),
    lair = 0.0,
    hd = (7,7,3),
    attacks = [(8,2,0)],
    m_resist = 0.0,
    iq = 'High',
    align = 'CG',
    size = 'L',
    special = [],
    exceptional = ['Create visual/audial illusion w/o concentration, last until touched or dispelled',
        'Become Invisible','Assume gaseous form','Wind Walk',
        'Form Whirlwind 1 turn cast (cone 1"base 3"top 7"high) last 1 round'+
        '\n  2d12 against non-aerial, instant kill under 2HD creatures'],
    notes = 'Can Create Nutrious Food 1/day for 2-12 people'+
        '\n  Create Water or Wine 1/day 2-12 people'+
        '\n Create soft goods or wooden items (16 cub ft, 9 cub ft) permanence'+
        '\n Create metal items of 1000g.p. weight, gold lasts 24 hrs, djinni steel 1 hr'+
        '\n Attacks from air element creatures -1 damage -1 to hit'+
        '\n 1% of Djinni are Noble Djinni who may grant 3 wishes (10HD,3-24damage,3-18 whirlwind)'
),
CreatureType('War Dog',
    num = (1,1),
    ac = 6,
    move = Move(12),
    lair = 0.0,
    hd = (2,2,2),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = []
),
CreatureType('Wild Dog',
    num = (4,16),
    ac = 7,
    move = Move(15),
    lair = 0.0,
    hd = (1,1,1),
    attacks = [(4,1,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = [],
    notes = 'Can be tamed if seperated from pack'
),
CreatureType('Dolphin',
    num = (2,20),
    ac = 5,
    move = Move(0,water=30),
    lair = 0.0,
    hd = (2,2,2),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'LG',
    size = 'M',
    special = [],
    exceptional = [],
    notes = '10% form communites. 75% of communities have 1d4 additional communities'
        '\n  within 5 miles. 2-5 swordfish or 1-3 narwhales act as guards'+
        '\n  Will help humans in distress. Attack sharks unless severely outnumbered.'
),
CreatureType('Doppleganger',
    num = (3,12),
    ac = 5,
    move = Move(9),
    lair = 0.2,
    hd = (4,4,0),
    attacks = [(12,1,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'NN',
    size = 'M',
    special = ['Surprise on 1-4',
    'Surprised parties cannot distinguish between mimicked creature',
    'Immune to sleep and charm',
    'Save as 10th level fighters',
    'Can use ESP',
    'Imitate others with 90% accuracy'
   ],
    exceptional = ['Can shape change into any observed humanoid 4ft to 8ft tall'],
    notes = 'Try to kill and take place of mimicked humanoids'
),
DragonType('Black Dragon',
    num = (1,4),
    ac = 3,
    move = Move(12,air=24),
    lair = 0.3,
    hd = (6,6,0),
    attacks = [(4,1,0),(4,1,0),(6,3,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'NE',
    size = 'L',
    special = [],
    exceptional = [
    'Acid breath 1/2" wide stream extending 6" in a straight line'+
    '\n  for damage equal to dragon\'s HP (half if save vs breath)'],
    speak = 0.3,
    magic = 0.1,
    sleep = 0.5,
    notes = 'Weak to earth and water attacks (+1 to hit and damage)'
),
DragonType('Blue Dragon',
    num = (1,4),
    ac = 2,
    move = Move(9,air=24),
    lair = 0.5,
    hd = (8,8,0),
    attacks = [(6,1,0),(6,1,0),(8,3,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'LE',
    size = 'L',
    special = ['Resistant to water and electric attack (-1 to hit and damage)'],
    exceptional = ['Lightning breath 1/2" wide bolt extending 10" in a straight line'+
        '\n for damage equal to dragon\'s HP (half if save vs breath)'],
    speak = 0.6,
    magic = 0.3,
    sleep = 0.3,
    notes = 'Weak to fire attacks (+1 to hit and damage)'
),
DragonType('Brass Dragon',
    num = (1,4),
    ac = 2,
    move = Move(12,air=24),
    lair = 0.25,
    hd = (6,6,0),
    attacks = [(4,1,0),(4,1,0),(4,4,0)],
    m_resist = 0.0,
    iq = 'High',
    align = 'CG',
    size = 'L',
    special = [],
    exceptional = ['Sleep gas breath cone 7" from mouth with ending diameter 2"',
        'Fear gas breath cloud 4" wide 5" across 2" deep'],
    speak = 0.3,
    magic = 0.3,
    sleep = 0.5,
    notes = 'Breath attack saves are at +2 for small, -2 for huge dragons.'
),
DragonType('Bronze Dragon',
    num = (1,4),
    ac = 0,
    move = Move(9,air=24),
    lair = 0.45,
    hd = (8,8,0),
    attacks = [(6,1,0),(6,1,0),(4,6,0)],
    m_resist = 0.0,
    iq = 'Exceptional',
    align = 'LG',
    size = 'L',
    special = [],
    exceptional = ['Lightning breath 10" long 1/2" wide',
        'Repulsion gas cloud 2" long 3" wide 3" high causing movement away for 6 rds'],
    speak = 0.6,
    magic = 0.6,
    sleep = 0.25,
    notes = 'Often assume form of an animal to observe humans.'
),
CreatureType('Chromatic Dragon (Tiamat)',
    num = (1,1),
    ac = 0,
    move = Move(12,air=24),
    lair = 0.9,
    hd = (0,0,128),
    attacks = [(8,2,0),(8,2,2),(10,2,0),(8,3,0),(10,3,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Genius',
    align = 'LE',
    size = 'L',
    special = ['Can travel astrally or ethereally'],
    exceptional = ['Cold breath 56HP 1/day','Acid breath 64HP 1/day',
        'Gas breath 72HP 1/day','Lightning breath 80HP 1/day',
        'Fire breath 88HP 1/day',
        'White head has two 1st level spells',
        'Black head has two 2nd level spells',
        'Green head has two 3rd level spells',
        'Blue head has two 4th level spells',
        'Red head has two 5th level spells'],
    notes = 'Will be caught sleeping 10% of the time.'+
        '\n  In lair, will have a huge adult white,black,green,blue,red dragon with speech and spells'+
        '\n  Each head can take 16HP before wilting, regenerating in 1 day'+
        '\n  Her main body can take 48HP before she is sent to Hell or slain (if fought in hell)'
),
DragonType('Copper Dragon',
    num = (1,4),
    ac = 1,
    move = Move(9,air=24),
    lair = 0.35,
    hd = (7,7,0),
    attacks = [(4,1,0),(4,1,0),(4,5,0)],
    m_resist = 0.0,
    iq = 'High',
    align = 'CG',
    size = 'L',
    special = [],
    exceptional = [
    'Acid breath 1/2" wide stream extending 7" in a straight line'+
    '\n  for damage equal to dragon\'s HP (half if save vs breath)',
    'Gas cloud breath 3" long by 2" wide by 2" deep which slows creatures movement and attack by 1/2 6rds'],
    speak = 0.45,
    magic = 0.4,
    sleep = 0.4
),
DragonType('Gold Dragon',
    num = (1,3),
    ac = -2,
    move = Move(12,air=30),
    lair = 0.65,
    hd = (10,10,0),
    attacks = [(8,1,0),(8,1,0),(6,6,0)],
    m_resist = 0.0,
    iq = 'Genius',
    align = 'LG',
    size = 'L',
    special = ['Can polymorph into human or animal'],
    exceptional = ['Fire breath 9"x3" cone',
        'Chlorine gas breath 5"x4"x3" cloud'],
    speak = 0.9,
    magic = 1.0,
    sleep = 0.1,
    notes = 'Always have lairs of solid stone, cave or castle.'
),
DragonType('Green Dragon',
    num = (1,4),
    ac = 2,
    move = Move(9,air=24),
    lair = 0.4,
    hd = (7,7,0),
    attacks = [(6,1,0),(6,1,0),(10,2,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'LE',
    size = 'L',
    special = [],
    exceptional = ['Gas cloud breath 5"x4"x3"'],
    speak = 0.45,
    magic = 0.2,
    sleep = 0.4,
    notes = 'Weak to air attacks (+1 to hit and damage)'
),
CreatureType('Platinum Dragon (Bahamut)',
    num = (1,1),
    ac = -3,
    move = Move(9,air=30),
    lair = 0.75,
    hd = (0,0,168),
    attacks = [(6,2,0),(6,2,0),(8,6,0)],
    m_resist = 0.0,
    iq = 'Supra-Genius',
    align = 'LG',
    size = 'L',
    special = ['Shape change','Astral and etheral travel'],
    exceptional = ['Cold breath 8"x3" 2/day -3 save',
        'Vapor breath cloud causing gaseous form for 12 turns 2/day -3 save',
        'Sonic vibration which disintegrates up to 150 HP 2/day -3 save',
        '2 magic 1 clerical 1st level spells per day',
        '2 magic 1 clerical 2nd level spells per day',
        '2 magic 1 clerical 3rd level spells per day',
        '2 magic 1 clerical 4th level spells per day',
        '2 magic 1 clerical 5th level spells per day',
        '2 magic 1 clerical 6th level spells per day',
        '2 magic 1 clerical 7th level spells per day',
        'Has spellbooks listing all known magic spells'],
    notes = '5% chance to be caught sleeping'+
        '\n Is accompanied by seven huge ancient gold dragons 90% of the time'
),
DragonType('Red Dragon',
    num = (1,4),
    ac = -1,
    move = Move(9,air=24),
    lair = 0.6,
    hd = (9,9,0),
    attacks = [(8,1,0),(8,1,0),(10,3,0)],
    m_resist = 0.0,
    iq = 'Exceptional',
    align = 'CE',
    size = 'L',
    special = ['Resistant to air and fire attacks (-1 to hit and damage)'],
    exceptional = ['Fire breath cone 9"x3"'],
    speak = 0.75,
    magic = 0.4,
    sleep = 0.2,
    notes = 'Weak to earth and water attacks (+1 to hit and damage)'
),
DragonType('Silver Dragon',
    num = (1,4),
    ac = -1,
    move = Move(9,air=24),
    lair = 0.55,
    hd = (9,9,0),
    attacks = [(6,1,0),(6,1,0),(6,5,0)],
    m_resist = 0.0,
    iq = 'Exceptional',
    align = 'LG',
    size = 'L',
    special = ['May polymorph to human or animal'],
    exceptional = ['Frost breath cone 8"x3"',
        'Paralyzing gas cloud breath 5"x4"x2"'],
    speak = 0.75,
    magic = 0.75,
    sleep = 0.15
),
DragonType('White Dragon',
    num = (1,4),
    ac = 3,
    move = Move(12,air=30),
    lair = 0.2,
    hd = (5,5,0),
    attacks = [(4,1,0),(4,1,0),(8,2,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'CE',
    size = 'L',
    special = ['Resistant to earth and water attacks (-1 to hit and damage)'],
    exceptional = ['Frost breath cone 7"x2.5"'],
    speak = 0.2,
    magic = 0.05,
    sleep = 0.6,
    notes = 'Weak to fire and electric attacks (+1 to hit and damage)'
),
CreatureType('Dragonne',
    num = (1,1),
    ac = 6,
    move = Move(15,air=9),
    lair = 0.4,
    hd = (9,9,0),
    attacks = [(8,1,0),(8,1,0),(6,3,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = [
        'May roar causing weakness to all within 12" (save v paralyze)'+
        '\n  Deafens all within 3". Both effects last for 2d6 rounds'+
        '\n  Weakened creatures lose 50% STR, deafened creatures strike at -1'],
    notes = 'May only fly short distances (1-3 turns)'
),
DragonType('Dragon Turtle',
    num = (1,1),
    ac = 0,
    move = Move(3,water=9),
    lair = 0.05,
    hd = (12,12,0),
    attacks = [(6,2,0),(6,2,0),(8,4,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Breath steam cloud 6"x4"x4" causing damage equal to HP (half if save)'],
    notes = '95% to capsize small ship, 50% large ship. Speak only their own language.',
),
CreatureType('Dryad',
    num = (1,6),
    ac = 9,
    move = Move(12),
    lair = 0.1,
    hd = (2,2,0),
    attacks = [(4,1,0)],
    m_resist = 0.0,
    iq = 'High',
    align = 'NN',
    size = 'M',
    special = ['Can dimension door through trees back to their host tree'],
    exceptional = ['Can charm person -3 save (will always against 16CHR males)'],
    notes = 'Are linked to a large oak dryad tree. Speak dryad, elven, pixie, sprite, plant'+
        '\n  Cannot dimension door if surprised. Can take away a charmed character.'+
        '\n Characters taken have a 50% chance to never return, or return in 1-4 years'+
        '\n Shy and non-violent. Carry daggers.'
),
CreatureType('Dwarf',
    num = (40,400),
    ac = 4,
    move = Move(6),
    lair = 0.5,
    hd = (1,1,0),
    attacks = [(8,1,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'LG',
    size = 'S',
    special = ['Save at 4 levels higher','Infravision 60ft'],
    exceptional = [],
    notes = 'For every 40 dwarves there will be a fighter level 2-6 (random treat 1 as 2)'+
        '\n  If 160+ there will be a 6th as chief and 4th as lieutenant'+
        '\n  If 200+ there will be a fighter(3-6)/cleric(4-7)'+
        '\n  If 320+ there will be 8th fighter, 7th fighter, 6fighter/7cleric and two 4th fighter/clerics'+
        '\n  If in lair, add 2-12 fighters level 2-5, 2-8 fighter/clerics level 2-4,'+
        '\n  as well as additional 50% female and 25% young.'+
        '\n  Typically armored with chainmail and shield, with the following weapons:'+
        '\n  15% sword & light crossbow, 10% sword & polearm, 20% sword & spear,'+
        '\n  10% axe & heavy crossbow, 25% axe & hammer, 10% hammer & pick'+
        '\n  For leveled characters following chances of magical items:'+
        '\n  10% per fighter level of magic armor and/or weapons'+
        '\n  10% per cleric level of 1-4 of (potions,cleric scroll, ring, wand/staff/rod, misc.)'+
        '\n  All leveled dwarves will have plate armor.'+
        '\n  60% likely to have tamed animals. 25% 5d4 wolves, 75% 2d4 brown bears'+
        '\n  Speak dwarvish, gnome, kobold, orc. 75% speak common'
),
CreatureType('Giant Eagle',
    num = (1,20),
    ac = 7,
    move = Move(3,air=48),
    lair = 0.2,
    hd = (4,4,0),
    attacks = [(6,1,0),(6,1,0),(6,2,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'NN',
    size = 'M',
    special = ['Never surprised during the day and outside lair',
        'Can dive from 50+ft for +4 hit double claw damage, but no beak attack'],
    exceptional = [],
    notes = '50% chance of having 1d4 young or eggs per nest, 1 nest per 2 eagles'+
        '\n  Will attack anything within 50ft of nest'+
        '\n  Have limited telepathy. Speak eagle.'
),
CreatureType('Ear Seekers',
    num = (1,4),
    ac = 9,
    move = Move(1),
    lair = 0.9,
    hd = (0,0,1),
    attacks = [],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = ['Eggs hatch in 4d6 hours. Larva start eating flesh killing host 90%'],
    notes = 'Crawl into ears and lay d8+8 eggs, before crawling out and dying.'+
        '\n A cure disease spell will destroy the eggs.'
),
CreatureType('Freshwater Electric Eel',
    num = (1,3),
    ac = 9,
    move = Move(0,water=12),
    lair = 0.0,
    hd = (2,2,0),
    attacks = [(3,1,0)],
    m_resist = 0.0,
    iq = '',
    align = 'NN',
    size = 'M',
    special = ['Immune to electricity'],
    exceptional = ['Jolt 15ft radius, within 5ft: 3d8, 10ft:2d8, 15ft 1d8 1/six turns'],
),
CreatureType('Saltwater Electric Eel',
    num = (1,3),
    ac = 9,
    move = Move(0,water=12),
    lair = 0.0,
    hd = (4,4,0),
    attacks = [(6,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'M',
    special = ['Immune to electricity'],
    exceptional = ['Jolt 15ft radius, within 5ft: 6d8, 10ft:4d8, 15ft 2d8 1/six turns'],
),
CreatureType('Giant Eel',
    num = (1,4),
    ac = 6,
    move = Move(0,water=9),
    lair = 0.0,
    hd = (5,5,0),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'M',
    special = [],
    exceptional = []
),
CreatureType('Weed Eel',
    num = (10,60),
    ac = 8,
    move = Move(0,water=15),
    lair = 1.0,
    hd = (1,1,-1),
    attacks = [(1,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = ['On bite, save vs poison or die']
),
CreatureType('Efreeti',
    num = (1,1),
    ac = 2,
    move = Move(9,air=24),
    lair = 0.0,
    hd = (10,10,0),
    attacks = [(8,3,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'NN',
    size = 'L',
    special = ['Detect magic','Produce Flame',
        'Immune to normal fire, magic fire at -1 hit and damage'],
    exceptional = ['Become invisible 1/day','Assume gaseous form 1/day',
        'Enlarge (as 10th level MU) 1/day','Polymorph self 1/day',
        'Create visual/audial illusion without concentration 1/day',
        'Wall of Fire 1/day','Pyrotechnics'],
    notes = 'Hate Djinni. Can be forced to serve 1001 days or until 3 wishes granted.'+
        '\n  Native to Elemental Plane of Fire'
),
#TODO: adjust hit die based on conjuring method
CreatureType('Air Elemental',
    num = (1,1),
    ac = 2,
    move = Move(36,air=36),
    lair = 0.0,
    hd = (8,8,0),
    attacks = [(10,2,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'L',
    special = ['+1 hit +2 damage fighting in the air'],
    exceptional = ['Requires +2 to hit or 4+HD',
        'Form whirlwind 2"x6"xHD", lasts 1 rd killing <3HD, 2d8 3+HD (1 turn cast)']
),
CreatureType('Earth Elemental',
    num = (1,1),
    ac = 2,
    move = Move(6),
    lair = 0.0,
    hd = (8,8,0),
    attacks = [(8,4,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Requires +2 to hit'],
    notes = '-2 damage each die against airborne opponents. Act as battering ram against structures 2-8HP'
),
CreatureType('Fire Elemental',
    num = (1,1),
    ac = 2,
    move = Move(12),
    lair = 0.0,
    hd = (8,8,0),
    attacks = [(8,3,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'L',
    special = ['Set fire to flammable objects on touch'],
    exceptional = ['+2 or better weapon to hit'],
    notes = '-1 damage on each die against fire opponents'
),
CreatureType('Water Elemental',
    num = (1,1),
    ac = 2,
    move = Move(6,water=18),
    lair = 0.0,
    hd = (8,8,0),
    attacks = [(6,5,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'NN',
    size = 'L',
    special = ['Can stop 1 ton of ship per HD or slow ratio tons/HP'],
    exceptional = [],
    notes = 'Cannot go further than 6" from water, outside water -1 damage per die'
),
CreatureType('Asiatic Elephant',
    num = (1,20),
    ac = 6,
    move = Move(12),
    lair = 0.0,
    hd = (10,10,0),
    attacks = [(6,2,0),(6,2,0),(6,2,0),(6,2,0),(6,2,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Can fight multiple opponents simultaneously (2 attacks each)'],
    exceptional = [],
    notes = 'Ogre sized or larger will not be affected by trunk attacks.'+
        '\n  Afraid of fire. Can easily break gates. Can be tamed.'+
        '\n  If more than 10 encountered, 1d4 young from 20% to 70% mature in herd'+
        '\n  If one encountered, it is rogue. 90% attack chance, at least 6HP per die'
),
CreatureType('Loxodont African Elephant',
    num = (1,12),
    ac = 6,
    move = Move(15),
    lair = 0.0,
    hd = (11,11,0),
    attacks = [(8,2,0),(8,2,0),(6,2,0),(6,2,0),(6,2,0)],
    m_resist = 0.0,
    iq = 'semi',
    align = 'NN',
    size = 'L',
    special = ['Can fight multiple opponents simultaneously (2 attacks each)'],
    exceptional = ['Ogre sized or larger will not be affected by trunk attacks.'+
        '\n  Afraid of fire. Can easily break gates. Can be tamed.'+
        '\n  If more than 6 encountered, 1d4 young from 20% to 70% mature in herd'+
        '\n  If one encountered, it is rogue. 90% attack chance, at least 6HP per die']
),
#TODO: Additional Elf notes and subraces
CreatureType('Elf',
    num = (20,200),
    ac = 5,
    move = Move(12),
    lair = 0.1,
    hd = (1,1,1),
    attacks = [(10,1,1)],
    m_resist = 0.0,
    iq = 'High',
    align = 'CG',
    size = 'M',
    special = ['+1 hit with bow or sword','90% sleep/charm resistance',
        'Surprise on 1-4','Blend into vegetation as invisibility when not attacking',
        'Can move, fire and retreat in one round'],
    exceptional = []
),
CreatureType('Ettin',
    num = (1,4),
    ac = 3,
    move = Move(12),
    lair = 0.2,
    hd = (10,10,0),
    attacks = [(8,2,0),(6,3,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'L',
    special = ['Surprised only on a 1'],
    exceptional = []
),
CreatureType('Floating Eye',
    num = (1,12),
    ac = 9,
    move = Move(0,water=30),
    lair = 0.0,
    hd = (1,1,-4),
    attacks = [],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = ['Paralyzing gaze'],
    notes = 'Usually accompanied by predatory fish, as they have a symbiotic relationship'
),
CreatureType('Eye of the Deep',
    num = (1,1),
    ac = 5,
    move = Move(0,water=6),
    lair = 0.2,
    hd = (10,12,0),
    attacks = [(4,2,0),(4,2,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'LE',
    size = 'L',
    special = [],
    exceptional = ['Central eye: stun 2d4 rds ray cone 1/2" at eye 3"x2"diameter',
        'Create illusion using both smaller eyes','Left eye:hold person',
        'Right eye: hold monster'],
    notes = 'Severed eyestalks regenerate in 1 week'
),
CreatureType('Flightless Bird',
    num = (2,20),
    ac = 7,
    move = Move(18),
    lair = 0.0,
    hd = (1,3,0),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'M',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = [],
    notes = 'Will try to flee before fighting'
),
CreatureType('Giant Frog',
    num = (5,40),
    ac = 7,
    move = Move(3,water=9),
    lair = 0.0,
    hd = (1,3,0),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'M',
    special = ['Surprise on 1-4.'],
    exceptional = ['Tongue strike at +4, no damage but draws prey to mouth'+
        '\n  Creatures hit with tongue may attack it,'+
        '\n  the frog will withdraw and not attack that creature again,'+
        '\n  If not struck, draws creature in next melee round for full damage'+
        '\n  If creature weighs more than frog, not drawn in until 3rd round'+
        '\n  If creature weight 2x more than frog, frog will release on 3rd round',
        'Can swallow whole on a 20 roll. 3 chances to cut out,'+ 
        '\n  (takes 18 or higher hit with edged weapon) killing the frog.'+
        '\n  1/3 chance of damaging swallowed creature when you strike the frog outside.'],
    notes = 'Retreat when wounded. Fear fire. Can jump 30ft high 45deg from facing'+
        '\n  Variations:'+
        '\n  1HD: 50lbs, 1-3 damage, 6ft tongue, 18" leap, S size'+
        '\n  2HD: 150lbs, 1-6 damage, 12ft tongue, 14" leap, S size'+
        '\n  3HD: 250lbs, 2-8 damage, 18ft tongue, 10" leap, M size'
),
CreatureType('Killer Frog',
    num = (3,18),
    ac = 8,
    move = Move(6,water=12),
    lair = 0.0,
    hd = (1,1,4),
    attacks = [(2,1,0),(2,1,0),(4,1,1)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = ['Surprise on 1-4.'],
    exceptional = ['Tongue strike at +4, no damage but draws prey to mouth'+
        '\n  Creatures hit with tongue may attack it,'+
        '\n  the frog will withdraw and not attack that creature again,'+
        '\n  If not struck, draws creature in next melee round for full damage'+
        '\n  If creature weighs more than frog, not drawn in until 3rd round'+
        '\n  If creature weight 2x more than frog, frog will release on 3rd round',
        'Can swallow whole on a 20 roll. 3 chances to cut out,'+ 
        '\n  (takes 18 or higher hit with edged weapon) killing the frog.'+
        '\n  1/3 chance of damaging swallowed creature when you strike the frog outside.'],
    notes = 'Retreat when wounded. Fear fire. Can jump 30ft high 45deg from facing'+
        '\n  50lbs, 6ft tongue, 18" leap'
),
CreatureType('Poisonous Frog',
    num = (2,12),
    ac = 8,
    move = Move(3,water=9),
    lair = 0.0,
    hd = (1,1,0),
    attacks = [(1,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = ['Surprise on 1-4.'],
    exceptional = ['Poison skin and bite (save at +4 or die)',
        'Tongue strike at +4, no damage but draws prey to mouth'+
        '\n  Creatures hit with tongue may attack it,'+
        '\n  the frog will withdraw and not attack that creature again,'+
        '\n  If not struck, draws creature in next melee round for full damage'+
        '\n  If creature weighs more than frog, not drawn in until 3rd round'+
        '\n  If creature weight 2x more than frog, frog will release on 3rd round',
        'Can swallow whole on a 20 roll. 3 chances to cut out,'+ 
        '\n  (takes 18 or higher hit with edged weapon) killing the frog.'+
        '\n  1/3 chance of damaging swallowed creature when you strike the frog outside.'],
    notes = 'Retreat when wounded. Fear fire. Can jump 30ft high 45deg from facing'+
        '\n  50lbs, 6ft tongue, 18" leap'
),
CreatureType('Violet Fungi',
    num = (1,4),
    ac = 7,
    move = Move(1),
    lair = 0.0,
    hd = (3,3,0),
    attacks = [(1,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'S',
    special = [],
    exceptional = ['Rot flesh in 1 round unless save vs poison or Cure Disase'],
    notes = 'Have 1-4 branches, size varies from 4ft-7ft with branch range 1ft-4ft'+
        '\n  Are accompanied by Shriekers 75% of the time. Grow on rotted flesh.'
),
CreatureType('Giant Gar',
    num = (1,6),
    ac = 3,
    move = Move(0,water=30),
    lair = 0.0,
    hd = (8,8,0),
    attacks = [(4,5,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Swallow whole on 20 roll. 5% death chance per round'+
        '\n  Must damage 25% total HP with edged weapon to cut out'+
        '\n  Piercing attacks on gar have 20% chance of striking swallowed'],
),
CreatureType('Gargoyle',
    num = (2,16),
    ac = 5,
    move = Move(9,air=15),
    lair = 0.2,
    hd = (4,4,4),
    attacks = [(3,1,0),(3,1,0),(6,1,0),(4,1,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'M',
    special = ['+1 required to hit.'],
    exceptional = [],
    notes = '90% likely to attack'
),
CreatureType('Kopoacinth',
    num = (2,16),
    ac = 5,
    move = Move(9,water=15),
    lair = 0.2,
    hd = (4,4,4),
    attacks = [(3,1,0),(3,1,0),(6,1,0),(4,1,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'M',
    special = ['+1 required to hit.'],
    exceptional = [],
    notes = '90% likely to attack'
),
CreatureType('Gas Spore',
    num = (1,3),
    ac = 9,
    move = Move(3,air=3),
    lair = 0.0,
    hd = (0,0,1),
    attacks = [(1,1,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['On hit, explodes 20ft radius for 6d6 (half when save vs wand)'+
        '\n  On successful attack, infect victim. If victim does not get'+
        '\n  a Cure Disease in 24 hours, they die and sprout 2d4 more spores.'],
    notes = 'At >10ft, 90% likely to be confused for a beholder.'+
        '\n  25% likely at close range'
),
CreatureType('Gelatinous Cube',
    num = (1,1),
    ac = 8,
    move = Move(6),
    lair = 0.0,
    hd = (4,4,0),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Surprise on 1-3','Immune to cold unless save,'+
        '\n  then 50% slow and only do 1d4 damage',
        'Immune to electricity, fear, hold, paralyzation, polymorph and sleep'],
    exceptional = ['On hit save vs paralyze or be out 5d4 rds']
),
CreatureType('Ghast',
    num = (1,6),
    ac = 4,
    move = Move(15),
    lair = 0.1,
    hd = (4,4,0),
    attacks = [(4,1,0),(4,1,0),(8,1,0)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'CE',
    size = 'M',
    special = ['Exude a stench causing -2 to hit unless save vs poison',
        'Undead, so immune to charm and sleep'],
    exceptional = ['Attacks cause paralyzation like ghouls'],
    notes = 'Iron causes double damage against ghasts.'+
        '\n  Protect evil only works if also using cold iron'+
        '\n  Usually accompanied (60% chance) by pack of ghouls'
),
CreatureType('Ghost',
    num = (1,1),
    ac = 0,
    move = Move(9),
    lair = 0.25,
    hd = (10,10,0),
    attacks = [(1,1,0)],
    m_resist = 0.0,
    iq = 'High',
    align = 'LE',
    size = 'M',
    special = ['In semi-material form, requires silver (50% damage) or magic to hit',
        'Ages 10-40 years on hit.',
        'Spells only affect it when caster is ethereal even when semi-material'],
    exceptional = ['Sight ages 10 years and fears for 2d6 turns unless save vs magic'+
        '\n  >6th Clerics are immune, >8th anyone gets +2 to save'],
    notes = 'Attacks with magic jar 6". If fails, becomes corporeal to attack.'+
        '\n  Can only be combatted telepathically or ethereally when ethereal.'+
        '\n  Anyone killed by a ghost is permanently dead.'
),
CreatureType('Ghoul',
    num = (2,24),
    ac = 6,
    move = Move(9),
    lair = 0.2,
    hd = (2,2,0),
    attacks = [(3,1,0),(3,1,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'M',
    special = ['Undead: immune to sleep and charm'],
    exceptional = ['Attack paralyzed unless save (no effect on elves)'],
    notes = 'Never become afraid'
),
CreatureType('Lacedon',
    num = (2,24),
    ac = 6,
    move = Move(9,water=9),
    lair = 0.2,
    hd = (2,2,0),
    attacks = [(3,1,0),(3,1,0),(6,1,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'M',
    special = ['Undead: immune to sleep and charm'],
    exceptional = ['Attack paralyzed unless save (no effect on elves)'],
    notes = 'Never become afraid'
),
CreatureType('Cloud Giant',
    num = (1,6),
    ac = 2,
    move = Move(15),
    lair = 0.4,
    hd = (12,12,5),
    attacks = [(6,6,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'NN',
    size = 'L',
    special = ['Only surprised on 1 due to keen smell'],
    exceptional = ['Can hurl rocks as catapult 2d12 1" to 24"'],
    notes = 'When more than 1, 75% likely that 2nd is female(fire giant HD,attack) rest young'+
        '\n  If 6 encountered, two young will be full grown male and female'+
        '\n  60% chance of catching catapult like missiles.'+
        '\n  50% Neutral good, 50% Neutral Evil. 10% are very intelligent.'+
        '\n  Very intelligent giants dwell on cloud islands and can levitate 2/day'+
        '\n  Evil giants have 1-3 captive slaves 50% chance'+
        '\n  In lair, 60% likely to have 1-4 spotted lions'
),
CreatureType('Fire Giant',
    num = (1,8),
    ac = 3,
    move = Move(12),
    lair = 0.35,
    hd = (11,11,4),
    attacks = [(6,5,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'LE',
    size = 'L',
    special = [],
    exceptional = ['Hurl rock 1"-20" 2d10'],
    notes = 'In lair, 25% have 1-4 hell hounds'+
        '\n  If more than 4 in lair, rest are female (HD attack as Frost Giant)'+
        '\n  If more than 6, last are young (roll percentile)'
),
CreatureType('Frost Giant',
    num = (1,8),
    ac = 4,
    move = Move(12),
    lair = 0.3,
    hd = (10,10,3),
    attacks = [(6,4,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'CE',
    size = 'L',
    special = [],
    exceptional = ['Hurl rocks 1"-20" 2d10'],
    notes = '50% have 1-6 winter wolves in lair'+
        '\n  If >4 in lair, 5,6 are female (as stone giant) 7,8 are young'+
        '\n  Catch catapult like missiles 40%'
),
CreatureType('Hill Giant',
    num = (1,10),
    ac = 4,
    move = Move(12),
    lair = 0.25,
    hd = (8,8,2),
    attacks = [(8,2,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'L',
    special = ['Hurl rock 1"-20" 2d8'],
    exceptional = [],
    notes = '50% creature guards in lair (50% 2-8 dire wolf,'+
        '\n  30% 1-3 giant lizard, 20% 2-8 ogres)'+
        '\n  If >4 in lair 5,7,9 giantess(6HD ogre attack), 6,8,10 young'
        '\n  Catch large missiles 30%'
),
CreatureType('Stone Giant',
    num = (1,8),
    ac = 0,
    move = Move(12),
    lair = 0.0,
    hd = (9,9,2),
    attacks = [(6,3,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'NN',
    size = 'L',
    special = [],
    exceptional = ['Hurl rock 1"-30" 3d10'],
    notes = '90% likely to catch large missiles'+
        '\n  >4 in lair, 5,6 female (as hill giant) 7,8 young'+
        '\n  75% likely to have 1-4 cave bears in lair'
),
CreatureType('Storm Giant',
    num = (1,4),
    ac = 1,
    move = Move(15),
    lair = 0.55,
    hd = (15,15,5),
    attacks = [(6,7,0)],
    m_resist = 0.0,
    iq = 'Exceptional',
    align = 'CG',
    size = 'L',
    special = ['Levitate 2/day','Immune to electricity'],
    exceptional = ['Hurl lightning bolt 8d8 1/day',
        'Cast call lightning 3 bolts 10-15 d6 1/day'],
    notes = 'Can breath underwater. Cast predict weather 1/day'+
        '\n  Control winds 1/day, weather summoning 1/day'+
        '\n  30% have lair guards: 70% 1-2 rocs (mounted) 30% 1-4 griffons'+
        '\n  Underwater lairs can have 2-8 sea lions'
),
CreatureType('Gnoll',
    num = (20,200),
    ac = 5,
    move = Move(9),
    lair = 0.2,
    hd = (2,2,0),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'L',
    special = ['Infravision'],
    exceptional = [],
    notes = 'Leader type for every 20 gnolls.'+
        '\n  When >=100, there will be a chieftan and 2-12 guards'+
        '\n  In lair: chieftan, 5-20 guards, and 50% female 200% young'+
        '\n  All carry swords, plus 15% great bow, 35% pole arm, 15% 2H Sword,'+
        '\n  20% battle axe, 15% morning star'
),
CreatureType('Gnoll Leader',
    num = (1,1),
    ac = 5,
    move = Move(9),
    lair = 0.0,
    hd = (0,0,16),
    attacks = [(4,2,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'CE',
    size = 'L',
    special = ['Infravision'],
    exceptional = [],
    notes = 'Attack as 3HD creature'
),
CreatureType('Gnoll Chieftan',
    num = (1,1),
    ac = 3,
    move = Move(9),
    lair = 0.0,
    hd = (0,0,22),
    attacks = [(4,2,2)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'CE',
    size = 'L',
    special = ['Infravision'],
    exceptional = [],
    notes = 'Attack as 4HD creature'
),
CreatureType('Gnoll Guard',
    num = (2,12),
    ac = 4,
    move = Move(9),
    lair = 0.0,
    hd = (0,0,20),
    attacks = [(4,2,1)],
    m_resist = 0.0,
    iq = 'Low',
    align = 'CE',
    size = 'L',
    special = ['Infravision'],
    exceptional = [],
    notes = 'Attack as 3 HD creature'
),
CreatureType('Gnome',
    num = (40,400),
    ac = 5,
    move = Move(6),
    lair = 0.5,
    hd = (1,1,0),
    attacks = [(,,)],
    m_resist = 0.0,
    iq = 'Very',
    align = 'NG',
    size = 'S',
    special = ['Save vs magic & poison as 4 levels higher','Infravision'],
    exceptional = []
),
CreatureType('Giant Goat',
    num = (1,12),
    ac = 7,
    move = Move(18),
    lair = 0.0,
    hd = (3,3,1),
    attacks = [(8,2,0)],
    m_resist = 0.0,
    iq = 'Semi',
    align = 'NN',
    size = 'L',
    special = ['Charge for +4 damage'],
    exceptional = []
),
CreatureType('Goblin',
    num = (40,400),
    ac = 6,
    move = Move(6),
    lair = 0.4,
    hd = (1,1,-1),
    attacks = [(6,1,0)],
    m_resist = 0.0,
    iq = 'Average',
    align = 'LE',
    size = 'S',
    special = ['Infravision'],
    exceptional = [],
    notes = 'Attack at -1 in sunlight'
),
CreatureType('Clay Golem',
    num = (1,1),
    ac = 7,
    move = Move(7),
    lair = 0.0,
    hd = (0,0,50),
    attacks = [(10,3,0)],
    m_resist = 0.0,
    iq = 'Non',
    align = 'NN',
    size = 'L',
    special = ['Can be hasted for 3 rds 1/day (after one round of combat)',
        'Immune to non-blunt weapons, immune to spells except:'+
        '\n  Move earth: 12" knock back 3d12, disintegrate slow 50% 1d12,'+
        '\n  Earthquake: stop for 1 turn 5d10'],
    exceptional = ['Damage caused can only be healed naturally or by 17th cleric Heal'],
    notes = 'Attack as 11 HD'+
        '\n  1% cumulative chance per combat round of permanent control loss'+
        '\n  where golem will attack any living thing until destroyed'
)
]

if __name__ == '__main__':
    __main__()
    
    
    
    
    
    
    
    