from random import choice



def generateRelic():
    return choice(relics)

relics = [
'Axe of the Dwarvish Lords',
'Baba Yaga\'s Hut',
'Codex of the Infinite Planes',
'Good Crown of Might',
'Neutral Crown of Might',
'Evil Crown of Might',
'Crystal of the Ebon Flame',
'Cup and Talisman of Al\'Akbar',
'Eye of Vecna',
'The Hand of Vecna',
'Heward\'s Mystical Organ',
'Horn of Change',
'Invulnerable Coat of Arnd',
'Iron Flask of Tuerny the Merciless',
'Jacinth of Inestimable Beauty',
'Johydee\'s Mask',
'Kuroth\'s Quill',
'Mace of Cuthbert',
'Machine of Lum the Mad',
'Mighty Servant of Leuk-O',
'Orb of the Hatchling',
'Orb of the Wyrmkind',
'Orb of the Dragonette',
'Orb of the Dragon',
'Orb of the Great Serpent',
'Orb of the Firedrake',
'Orb of the Elder Wyrm',
'Orb of the Eternal Grand Dragon',
'Good Orb of Might',
'Neutral Orb of Might',
'Evil Orb of Might',
'Queen Ehlissa\'s Marvelous Nightingale',
'Recorder of Ye\'Cind',
'Ring of Gaxx',
'Part I of Rod of Seven Parts',
'Part II of Rod of Seven Parts',
'Part III of Rod of Seven Parts',
'Part IV of Rod of Seven Parts',
'Part V of Rod of Seven Parts',
'Part VI of Rod of Seven Parts',
'Part VII of Rod of Seven Parts',
'Good Sceptre of Might',
'Neutral Sceptre of Might',
'Evil Sceptre of Might',
'Sword of Kas',
'Tooth 1 of Dahlver-Nar',
'Tooth 2 of Dahlver-Nar',
'Tooth 3 of Dahlver-Nar',
'Tooth 4 of Dahlver-Nar',
'Tooth 5 of Dahlver-Nar',
'Tooth 6 of Dahlver-Nar',
'Tooth 7 of Dahlver-Nar',
'Tooth 8 of Dahlver-Nar',
'Tooth 9 of Dahlver-Nar',
'Tooth 10 of Dahlver-Nar',
'Tooth 11 of Dahlver-Nar',
'Tooth 12 of Dahlver-Nar',
'Tooth 13 of Dahlver-Nar',
'Tooth 14 of Dahlver-Nar',
'Tooth 15 of Dahlver-Nar',
'Tooth 16 of Dahlver-Nar',
'Tooth 17 of Dahlver-Nar',
'Tooth 18 of Dahlver-Nar',
'Tooth 19 of Dahlver-Nar',
'Tooth 20 of Dahlver-Nar',
'Tooth 21 of Dahlver-Nar',
'Tooth 22 of Dahlver-Nar',
'Tooth 23 of Dahlver-Nar',
'Tooth 24 of Dahlver-Nar',
'Tooth 25 of Dahlver-Nar',
'Tooth 26 of Dahlver-Nar',
'Tooth 27 of Dahlver-Nar',
'Tooth 28 of Dahlver-Nar',
'Tooth 29 of Dahlver-Nar',
'Tooth 30 of Dahlver-Nar',
'Tooth 31 of Dahlver-Nar',
'Tooth 32 of Dahlver-Nar',
'Throne of the Gods',
'Wand of Orcus'
]

if __name__ == '__main__':
    while True:
        input()
        print(generateRelic())
