# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=75)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('min_hd', models.PositiveSmallIntegerField()),
                ('max_hd', models.PositiveSmallIntegerField()),
                ('min_hp_mod', models.SmallIntegerField()),
                ('max_hp_mod', models.SmallIntegerField()),
                ('min_appearing', models.PositiveSmallIntegerField()),
                ('max_appearing', models.PositiveSmallIntegerField()),
                ('lair_chance', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('base_xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
    ]
