# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CreatureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=75)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('alt_names', models.CharField(max_length=500, null=True)),
                ('source', models.SmallIntegerField()),
                ('parent_creature', models.CharField(max_length=100, null=True)),
                ('sub_creatures', models.CharField(max_length=500, null=True)),
                ('min_appearing', models.PositiveSmallIntegerField()),
                ('max_appearing', models.PositiveSmallIntegerField()),
                ('lair_chance', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('treasure_types', models.CharField(max_length=100, null=True)),
                ('ac', models.SmallIntegerField()),
                ('ground_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('air_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('burrow_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('climb_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('web_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_hd', models.PositiveSmallIntegerField()),
                ('max_hd', models.PositiveSmallIntegerField()),
                ('min_hp_mod', models.SmallIntegerField()),
                ('max_hp_mod', models.SmallIntegerField()),
                ('attacks', models.CharField(max_length=300, null=True)),
                ('magic_resist', models.DecimalField(decimal_places=2, max_digits=4)),
                ('iq_class', models.SmallIntegerField()),
                ('alignment', models.CharField(max_length=2)),
                ('size_class', models.CharField(max_length=1)),
                ('level', models.IntegerField(null=True)),
                ('base_xp', models.IntegerField(default=0)),
                ('xp_per_hp', models.IntegerField(default=0)),
            ],
        ),
    ]
